# Generated by Django 4.1.5 on 2023-01-17 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0003_remove_city_state_city_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='State',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state', to='medicSearch.state'),
        ),
    ]
