# Generated by Django 4.1.5 on 2023-01-18 02:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicSearch', '0004_remove_city_state_profile_image_city_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='addresses',
            field=models.ManyToManyField(blank=True, null=True, related_name='addresses', to='medicSearch.address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialties',
            field=models.ManyToManyField(blank=True, null=True, related_name='specialties', to='medicSearch.speciality'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
