# Generated by Django 4.1.5 on 2023-02-01 03:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicSearch', '0006_alter_profile_addresses_alter_profile_favorites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='addresses',
            field=models.ManyToManyField(blank=True, null=True, related_name='addresses', to='medicSearch.address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialties',
            field=models.ManyToManyField(blank=True, null=True, related_name='specialties', to='medicSearch.speciality'),
        ),
    ]
